openapi: 3.0.0
info:
  version: 0.1.0
  title: Data Service
  description: Service to expose StackingUp DataDB.
  contact:
    name: StackingUp
    email: stackingup13@gmail.com
    url: 'https://stacking-up.github.io'
  license:
    name: MIT
    url: 'http://opensource.org/licenses/MIT'
paths:
  /api/v1/users:
    get:
      tags:
        - Users
      x-swagger-router-controller: UserController
      description: Returns all users
      operationId: getUsers
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/user'
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/errorModel'
  '/api/v1/users/{userId}':
    get:
      tags:
        - Users
      x-swagger-router-controller: UserController
      description: Returns user by id
      operationId: getUser
      parameters:
        - name: userId
          in: path
          description: User's id
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/user'
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/errorModel'
        '404':
          description: Not Found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/errorModel'
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/errorModel'
  '/api/v1/users/{userId}/items':
    get:
      tags:
        - Users
      x-swagger-router-controller: UserController
      description: Returns the items some user wants to store
      operationId: getUserItems
      parameters:
        - name: userId
          in: path
          description: User's id
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/item'
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/errorModel'
        '404':
          description: Not Found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/errorModel'
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/errorModel'
  '/api/v1/users/{userId}/items/{itemId}':
    get:
      tags:
        - Users
      x-swagger-router-controller: UserController
      description: Returns an item some user wants to store
      operationId: getUserItem
      parameters:
        - name: userId
          in: path
          description: User's id
          required: true
          schema:
            type: string
        - name: itemId
          in: path
          description: Item's id
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/item'
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/errorModel'
        '404':
          description: Not Found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/errorModel'
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/errorModel'
  '/api/v1/users/{userId}/ratings':
    get:
      tags:
        - Users
      x-swagger-router-controller: UserController
      description: Returns some user's ratings
      operationId: getUserRatings
      parameters:
        - name: userId
          in: path
          description: User's id
          required: true
          schema:
            type: string
        - name: filter
          in: query
          description: 'Filter for given, received or both'
          required: false
          schema:
            type: string
            enum:
              - given
              - received
              - all
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/rating'
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/errorModel'
        '404':
          description: Not Found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/errorModel'
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/errorModel'
  '/api/v1/users/{userId}/ratings/{ratingId}':
    get:
      tags:
        - Users
      x-swagger-router-controller: UserController
      description: Returns a rating some user has given or received
      operationId: getUserRating
      parameters:
        - name: userId
          in: path
          description: User's id
          required: true
          schema:
            type: string
        - name: ratingId
          in: path
          description: Rating's id
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/rating'
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/errorModel'
        '404':
          description: Not Found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/errorModel'
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/errorModel'
  '/api/v1/users/{userId}/spaces':
    get:
      tags:
        - Users
      x-swagger-router-controller: UserController
      description: Returns spaces some user has published
      operationId: getUserSpaces
      parameters:
        - name: userId
          in: path
          description: User's id
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/space'
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/errorModel'
        '404':
          description: Not Found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/errorModel'
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/errorModel'
  '/api/v1/users/{userId}/spaces/{spaceId}':
    get:
      tags:
        - Users
      x-swagger-router-controller: UserController
      description: Returns a space some user has published
      operationId: getUserSpace
      parameters:
        - name: userId
          in: path
          description: User's id
          required: true
          schema:
            type: string
        - name: spaceId
          in: path
          description: Space's id
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/space'
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/errorModel'
        '404':
          description: Not Found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/errorModel'
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/errorModel'
  '/api/v1/users/{userId}/rentals':
    get:
      tags:
        - Users
      x-swagger-router-controller: UserController
      description: Returns some user rentals
      operationId: getUserRentals
      parameters:
        - name: userId
          in: path
          description: User's id
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/rental'
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/errorModel'
        '404':
          description: Not Found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/errorModel'
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/errorModel'
  '/api/v1/users/{userId}/rentals/{rentalId}':
    get:
      tags:
        - Users
      x-swagger-router-controller: UserController
      description: Returns some user rental
      operationId: getUserRental
      parameters:
        - name: userId
          in: path
          description: User's id
          required: true
          schema:
            type: string
        - name: rentalId
          in: path
          description: Rental's id
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/rental'
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/errorModel'
        '404':
          description: Not Found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/errorModel'
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/errorModel'
  /api/v1/spaces:
    get:
      tags:
        - Spaces
      x-swagger-router-controller: SpaceController
      description: Returns all spaces
      operationId: getSpaces
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/space'
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/errorModel'
  '/api/v1/spaces/{spaceId}':
    get:
      tags:
        - Spaces
      x-swagger-router-controller: SpaceController
      description: Returns space by id
      operationId: getSpace
      parameters:
        - name: spaceId
          in: path
          description: Space's id
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/space'
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/errorModel'
        '404':
          description: Not Found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/errorModel'
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/errorModel'
  '/api/v1/spaces/{spaceId}/rentals':
    get:
      tags:
        - Spaces
      x-swagger-router-controller: SpaceController
      description: Returns some space rentals
      operationId: getSpaceRentals
      parameters:
        - name: spaceId
          in: path
          description: Space's id
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/rental'
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/errorModel'
        '404':
          description: Not Found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/errorModel'
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/errorModel'
  /api/v1/rentals:
    get:
      tags:
        - Rentals
      x-swagger-router-controller: RentalController
      description: Returns all rentals
      operationId: getRentals
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/rental'
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/errorModel'
  '/api/v1/rentals/{rentalId}':
    get:
      tags:
        - Rentals
      x-swagger-router-controller: RentalController
      description: Returns rental by id
      operationId: getRental
      parameters:
        - name: rentalId
          in: path
          description: Rental's id
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/rental'
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/errorModel'
        '404':
          description: Not Found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/errorModel'
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/errorModel'
components:
  schemas:
    errorModel:
      type: string
    user:
      type: object
      required:
        - id
        - name
        - surname
      properties:
        id:
          type: integer
          format: int32
        name:
          type: string
        surname:
          type: string
        birthDate:
          type: string
          format: date-time
        sex:
          type: string
          enum:
            - MALE
            - FEMALE
            - OTHER
        idcard:
          type: string
        phoneNumber:
          type: string
        location:
          type: string
        avatar:
          type: string
          format: binary
    item:
      type: object
      required:
        - type
        - dimensions
        - ownerId
      properties:
        type:
          type: string
          enum:
            - Muy grande
            - Grande
            - Mediano
            - Pequeño
        dimensions:
          type: string
        ownerId:
          type: integer
          format: int32
    rating:
      type: object
      required:
        - title
        - description
        - rating
        - reviewerId
        - receiverId
      properties:
        title:
          type: string
        description:
          type: string
        rating:
          type: integer
        reviewerId:
          type: integer
          format: int32
        receiverId:
          type: integer
          format: int32
    space:
      type: object
      required:
        - name
        - description
        - initialDate
        - location
        - dimensions
        - shared
        - ownerId
      properties:
        name:
          type: string
        description:
          type: string
        initialDate:
          type: string
          format: date-time
        finalDate:
          type: string
          format: date-time
        location:
          type: string
        dimensions:
          type: string
        priceHour:
          type: number
          format: double
        priceDay:
          type: number
          format: double
        priceMonth:
          type: number
          format: double
        shared:
          type: boolean
        ownerId:
          type: integer
          format: int32
        image:
          type: string
          format: binary
    rental:
      type: object
      required:
        - initialDate
        - finalDate
        - cost
        - type
        - meters
        - spaceId
        - renterId
      properties:
        initialDate:
          type: string
          format: date-time
        finalDate:
          type: string
          format: date-time
        cost:
          type: integer
        type:
          type: string
          enum:
            - HOUR
            - DAY
            - MONTH
        meters:
          type: number
          format: double
        spaceId:
          type: integer
          format: int32
        renterId:
          type: integer
          format: int32
